### ISSUE TITLE
FPVMI_AddViewModelToClient glitch. Wont remove model

### ISSUE THREAD

**Issue by hitmany** [Franc1sco/First-Person-View-Models-Interface#2]
Hello!

Thank you for great plugin again)
I have issue with FPVMI_AddViewModelToClient
When I trying to remove view model its wont be changed and blinking
But after I changing weapon and switching back to custom weapon its returns to original weapon model

https://www.youtube.com/watch?v=Ri7txgg51K8

**Comment by hitmany** [comment]
Any ideas? ))

**Comment by NomisCZ** [comment]
This should help you:

	// Give player Zeus, because FPMVKnife bug
	int zeus = GetPlayerWeaponSlot(client, 2);

	if(zeus != -1) {
		int taser = GivePlayerItem(client, "weapon_taser");
		EquipPlayerWeapon(client, taser);
	}
	
	RemovePlayerItem(client, zeus);
	RemoveEdict(zeus);
	FPVMI_RemoveViewModelToClient(client, "weapon_knife");

**Comment by hitmany** [comment]
Yes, thank you. I am using such temp fix. But I hope this big can be fixed
